# Generated by Django 6.0.2 on 2026-05-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message_related', related_query_name='sender_message_query', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Converstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converstation_id', models.IntegerField(editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('users', models.ManyToManyField(related_name='users_message_related', related_query_name='users_message_query', to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('messages', models.ManyToManyField(related_name='message_converstation_related', related_query_name='message_converstation_query', to='message.message', verbose_name='messages')),
            ],
            options={
                'verbose_name': 'converstation',
                'verbose_name_plural': 'converstations',
                'ordering': ('-date_created',),
            },
        ),
    ]
