from django.utils.translation import gettext_lazy as _

COUNTRIES = (
    ("AF", _("Afghanistan")),
    ("AX", _("Aland Islands")),
    ("AL", _("Albania")),
    ("DZ", _("Algeria")),
    ("AS", _("American Samoa")),
    ("AD", _("Andorra")),
    ("AO", _("Angola")),
    ("AI", _("Anguilla")),
    ("AQ", _("Antarctica")),
    ("AG", _("Antigua and Barbuda")),
    ("AR", _("Argentina")),
    ("AM", _("Armenia")),
    ("AW", _("Aruba")),
    ("AU", _("Australia")),
    ("AT", _("Austria")),
    ("AZ", _("Azerbaijan")),
    ("BS", _("Bahamas (The)")),
    ("BH", _("Bahrain")),
    ("BD", _("Bangladesh")),
    ("BB", _("Barbados")),
    ("BY", _("Belarus")),
    ("BE", _("Belgium")),
    ("BZ", _("Belize")),
    ("BJ", _("Benin")),
    ("BM", _("Bermuda")),
    ("BT", _("Bhutan")),
    ("BO", _("Bolivia (Plurinational State of)")),
    ("BQ", _("Bonaire, Sint Eustatius and Saba")),
    ("BA", _("Bosnia and Herzegovina")),
    ("BW", _("Botswana")),
    ("BV", _("Bouvet Island")),
    ("BR", _("Brazil")),
    ("IO", _("British Indian Ocean Territory")),
    ("BN", _("Brunei Darussalam")),
    ("BG", _("Bulgaria")),
    ("BF", _("Burkina Faso")),
    ("BI", _("Burundi")),
    ("CV", _("Cabo Verde")),
    ("KH", _("Cambodia")),
    ("CM", _("Cameroon")),
    ("CA", _("Canada")),
    ("KY", _("Cayman Islands")),
    ("CF", _("Central African Republic")),
    ("TD", _("Chad")),
    ("CL", _("Chile")),
    ("CN", _("China")),
    ("CX", _("Christmas Island")),
    ("CC", _("Cocos (Keeling) Islands")),
    ("CO", _("Colombia")),
    ("KM", _("Comoros")),
    ("CG", _("Congo")),
    ("CD", _("Congo (the Democratic Republic of the)")),
    ("CK", _("Cook Islands")),
    ("CR", _("Costa Rica")),
    ("CI", _("Côte d'Ivoire")),
    ("HR", _("Croatia")),
    ("CU", _("Cuba")),
    ("CW", _("Curaçao")),
    ("CY", _("Cyprus")),
    ("CZ", _("Czechia")),
    ("DK", _("Denmark")),
    ("DJ", _("Djibouti")),
    ("DM", _("Dominica")),
    ("DO", _("Dominican Republic")),
    ("EC", _("Ecuador")),
    ("EG", _("Egypt")),
    ("SV", _("El Salvador")),
    ("GQ", _("Equatorial Guinea")),
    ("ER", _("Eritrea")),
    ("EE", _("Estonia")),
    ("SZ", _("Eswatini")),
    ("ET", _("Ethiopia")),
    ("FK", _("Falkland Islands (Malvinas)")),
    ("FO", _("Faroe Islands")),
    ("FJ", _("Fiji")),
    ("FI", _("Finland")),
    ("FR", _("France")),
    ("GF", _("French Guiana")),
    ("PF", _("French Polynesia")),
    ("TF", _("French Southern Territories")),
    ("GA", _("Gabon")),
    ("GM", _("Gambia")),
    ("GE", _("Georgia")),
    ("DE", _("Germany")),
    ("GH", _("Ghana")),
    ("GI", _("Gibraltar")),
    ("GR", _("Greece")),
    ("GL", _("Greenland")),
    ("GD", _("Grenada")),
    ("GP", _("Guadeloupe")),
    ("GU", _("Guam")),
    ("GT", _("Guatemala")),
    ("GG", _("Guernsey")),
    ("GN", _("Guinea")),
    ("GW", _("Guinea-Bissau")),
    ("GY", _("Guyana")),
    ("HT", _("Haiti")),
    ("HM", _("Heard Island and McDonald Islands")),
    ("VA", _("Holy See")),
    ("HN", _("Honduras")),
    ("HK", _("Hong Kong")),
    ("HU", _("Hungary")),
    ("IS", _("Iceland")),
    ("IN", _("India")),
    ("ID", _("Indonesia")),
    ("IR", _("Iran (Islamic Republic of)")),
    ("IQ", _("Iraq")),
    ("IE", _("Ireland")),
    ("IM", _("Isle of Man")),
    ("IL", _("Israel")),
    ("IT", _("Italy")),
    ("JM", _("Jamaica")),
    ("JP", _("Japan")),
    ("JE", _("Jersey")),
    ("JO", _("Jordan")),
    ("KZ", _("Kazakhstan")),
    ("KE", _("Kenya")),
    ("KI", _("Kiribati")),
    ("KP", _("Korea (the Democratic People's Republic of)")),
    ("KR", _("Korea (the Republic of)")),
    ("KW", _("Kuwait")),
    ("KG", _("Kyrgyzstan")),
    ("LA", _("Lao People's Democratic Republic")),
    ("LV", _("Latvia")),
    ("LB", _("Lebanon")),
    ("LS", _("Lesotho")),
    ("LR", _("Liberia")),
    ("LY", _("Libya")),
    ("LI", _("Liechtenstein")),
    ("LT", _("Lithuania")),
    ("LU", _("Luxembourg")),
    ("MO", _("Macao")),
    ("MG", _("Madagascar")),
    ("MW", _("Malawi")),
    ("MY", _("Malaysia")),
    ("MV", _("Maldives")),
    ("ML", _("Mali")),
    ("MT", _("Malta")),
    ("MH", _("Marshall Islands")),
    ("MQ", _("Martinique")),
    ("MR", _("Mauritania")),
    ("MU", _("Mauritius")),
    ("YT", _("Mayotte")),
    ("MX", _("Mexico")),
    ("FM", _("Micronesia (Federated States of)")),
    ("MD", _("Moldova (the Republic of)")),
    ("MC", _("Monaco")),
    ("MN", _("Mongolia")),
    ("ME", _("Montenegro")),
    ("MS", _("Montserrat")),
    ("MA", _("Morocco")),
    ("MZ", _("Mozambique")),
    ("MM", _("Myanmar")),
    ("NA", _("Namibia")),
    ("NR", _("Nauru")),
    ("NP", _("Nepal")),
    ("NL", _("Netherlands (Kingdom of the)")),
    ("NC", _("New Caledonia")),
    ("NZ", _("New Zealand")),
    ("NI", _("Nicaragua")),
    ("NE", _("Niger")),
    ("NG", _("Nigeria")),
    ("NU", _("Niue")),
    ("NF", _("Norfolk Island")),
    ("MK", _("North Macedonia")),
    ("MP", _("Northern Mariana Islands")),
    ("NO", _("Norway")),
    ("OM", _("Oman")),
    ("PK", _("Pakistan")),
    ("PW", _("Palau")),
    ("PS", _("Palestine, State of")),
    ("PA", _("Panama")),
    ("PG", _("Papua New Guinea")),
    ("PY", _("Paraguay")),
    ("PE", _("Peru")),
    ("PH", _("Philippines")),
    ("PN", _("Pitcairn")),
    ("PL", _("Poland")),
    ("PT", _("Portugal")),
    ("PR", _("Puerto Rico")),
    ("QA", _("Qatar")),
    ("RE", _("Réunion")),
    ("RO", _("Romania")),
    ("RU", _("Russian Federation")),
    ("RW", _("Rwanda")),
    ("BL", _("Saint Barthélemy")),
    ("SH", _("Saint Helena, Ascension and Tristan da Cunha")),
    ("KN", _("Saint Kitts and Nevis")),
    ("LC", _("Saint Lucia")),
    ("MF", _("Saint Martin (French part)")),
    ("PM", _("Saint Pierre and Miquelon")),
    ("VC", _("Saint Vincent and the Grenadines")),
    ("WS", _("Samoa")),
    ("SM", _("San Marino")),
    ("ST", _("Sao Tome and Principe")),
    ("SA", _("Saudi Arabia")),
    ("SN", _("Senegal")),
    ("RS", _("Serbia")),
    ("SC", _("Seychelles")),
    ("SL", _("Sierra Leone")),
    ("SG", _("Singapore")),
    ("SX", _("Sint Maarten (Dutch part)")),
    ("SK", _("Slovakia")),
    ("SI", _("Slovenia")),
    ("SB", _("Solomon Islands")),
    ("SO", _("Somalia")),
    ("ZA", _("South Africa")),
    ("GS", _("South Georgia and the South Sandwich Islands")),
    ("SS", _("South Sudan")),
    ("ES", _("Spain")),
    ("LK", _("Sri Lanka")),
    ("SD", _("Sudan")),
    ("SR", _("Suriname")),
    ("SJ", _("Svalbard and Jan Mayen")),
    ("SE", _("Sweden")),
    ("CH", _("Switzerland")),
    ("SY", _("Syrian Arab Republic")),
    ("TW", _("Taiwan (Province of China)")),
    ("TJ", _("Tajikistan")),
    ("TZ", _("Tanzania, the United Republic of")),
    ("TH", _("Thailand")),
    ("TL", _("Timor-Leste")),
    ("TG", _("Togo")),
    ("TK", _("Tokelau")),
    ("TO", _("Tonga")),
    ("TT", _("Trinidad and Tobago")),
    ("TN", _("Tunisia")),
    ("TR", _("Türkiye")),
    ("TM", _("Turkmenistan")),
    ("TC", _("Turks and Caicos Islands")),
    ("TV", _("Tuvalu")),
    ("UG", _("Uganda")),
    ("UA", _("Ukraine")),
    ("AE", _("United Arab Emirates")),
    ("GB", _("United Kingdom of Great Britain and Northern Ireland")),
    ("UM", _("United States Minor Outlying Islands")),
    ("US", _("United States of America")),
    ("UY", _("Uruguay")),
    ("UZ", _("Uzbekistan")),
    ("VU", _("Vanuatu")),
    ("VE", _("Venezuela (Bolivarian Republic of)")),
    ("VN", _("Viet Nam")),
    ("VG", _("Virgin Islands (British)")),
    ("VI", _("Virgin Islands (U.S.)")),
    ("WF", _("Wallis and Futuna")),
    ("EH", _("Western Sahara")),
    ("YE", _("Yemen")),
    ("ZM", _("Zambia")),
    ("ZW", _("Zimbabwe")),
)

COUNTRY_CODES =(
    ("+93", _("+93 Afghanistan")),
    ("+358", _("+358 Åland Islands")),
    ("+355", _("+355 Albania")),
    ("+213", _("+213 Algeria")),
    ("+1-684", _("+1-684 American Samoa")),
    ("+376", _("+376 Andorra")),
    ("+244", _("+244 Angola")),
    ("+1-264", _("+1-264 Anguilla")),
    ("+672", _("+672 Antarctica")),
    ("+1-268", _("+1-268 Antigua and Barbuda")),
    ("+54", _("+54 Argentina")),
    ("+374", _("+374 Armenia")),
    ("+297", _("+297 Aruba")),
    ("+61", _("+61 Australia")),
    ("+43", _("+43 Austria")),
    ("+994", _("+994 Azerbaijan")),
    ("+1-242", _("+1-242 Bahamas")),
    ("+973", _("+973 Bahrain")),
    ("+880", _("+880 Bangladesh")),
    ("+1-246", _("+1-246 Barbados")),
    ("+375", _("+375 Belarus")),
    ("+32", _("+32 Belgium")),
    ("+501", _("+501 Belize")),
    ("+229", _("+229 Benin")),
    ("+1-441", _("+1-441 Bermuda")),
    ("+975", _("+975 Bhutan")),
    ("+591", _("+591 Bolivia")),
    ("+387", _("+387 Bosnia and Herzegovina")),
    ("+267", _("+267 Botswana")),
    ("+55", _("+55 Brazil")),
    ("+246", _("+246 British Indian Ocean Territory")),
    ("+673", _("+673 Brunei")),
    ("+359", _("+359 Bulgaria")),
    ("+226", _("+226 Burkina Faso")),
    ("+257", _("+257 Burundi")),
    ("+855", _("+855 Cambodia")),
    ("+237", _("+237 Cameroon")),
    ("+1", _("+1 Canada")),
    ("+238", _("+238 Cape Verde")),
    ("+1-345", _("+1-345 Cayman Islands")),
    ("+236", _("+236 Central African Republic")),
    ("+235", _("+235 Chad")),
    ("+56", _("+56 Chile")),
    ("+86", _("+86 China")),
    ("+61", _("+61 Christmas Island")),
    ("+61", _("+61 Cocos Islands")),
    ("+57", _("+57 Colombia")),
    ("+269", _("+269 Comoros")),
    ("+242", _("+242 Congo")),
    ("+243", _("+243 DR Congo")),
    ("+682", _("+682 Cook Islands")),
    ("+506", _("+506 Costa Rica")),
    ("+385", _("+385 Croatia")),
    ("+53", _("+53 Cuba")),
    ("+599", _("+599 Curacao")),
    ("+357", _("+357 Cyprus")),
    ("+420", _("+420 Czech Republic")),
    ("+45", _("+45 Denmark")),
    ("+253", _("+253 Djibouti")),
    ("+1-767", _("+1-767 Dominica")),
    ("+1-809", _("+1-809 Dominican Republic")),
    ("+670", _("+670 East Timor")),
    ("+593", _("+593 Ecuador")),
    ("+20", _("+20 Egypt")),
    ("+503", _("+503 El Salvador")),
    ("+240", _("+240 Equatorial Guinea")),
    ("+291", _("+291 Eritrea")),
    ("+372", _("+372 Estonia")),
    ("+251", _("+251 Ethiopia")),
    ("+500", _("+500 Falkland Islands")),
    ("+298", _("+298 Faroe Islands")),
    ("+679", _("+679 Fiji")),
    ("+358", _("+358 Finland")),
    ("+33", _("+33 France")),
    ("+689", _("+689 French Polynesia")),
    ("+241", _("+241 Gabon")),
    ("+220", _("+220 Gambia")),
    ("+995", _("+995 Georgia")),
    ("+49", _("+49 Germany")),
    ("+233", _("+233 Ghana")),
    ("+350", _("+350 Gibraltar")),
    ("+30", _("+30 Greece")),
    ("+299", _("+299 Greenland")),
    ("+1-473", _("+1-473 Grenada")),
    ("+1-671", _("+1-671 Guam")),
    ("+502", _("+502 Guatemala")),
    ("+44-1481", _("+44-1481 Guernsey")),
    ("+224", _("+224 Guinea")),
    ("+245", _("+245 Guinea-Bissau")),
    ("+592", _("+592 Guyana")),
    ("+509", _("+509 Haiti")),
    ("+504", _("+504 Honduras")),
    ("+852", _("+852 Hong Kong")),
    ("+36", _("+36 Hungary")),
    ("+354", _("+354 Iceland")),
    ("+91", _("+91 India")),
    ("+62", _("+62 Indonesia")),
    ("+98", _("+98 Iran")),
    ("+964", _("+964 Iraq")),
    ("+353", _("+353 Ireland")),
    ("+972", _("+972 Israel")),
    ("+39", _("+39 Italy")),
    ("+225", _("+225 Ivory Coast")),
    ("+1-876", _("+1-876 Jamaica")),
    ("+81", _("+81 Japan")),
    ("+962", _("+962 Jordan")),
    ("+7", _("+7 Kazakhstan")),
    ("+254", _("+254 Kenya")),
    ("+686", _("+686 Kiribati")),
    ("+965", _("+965 Kuwait")),
    ("+996", _("+996 Kyrgyzstan")),
    ("+856", _("+856 Laos")),
    ("+371", _("+371 Latvia")),
    ("+961", _("+961 Lebanon")),
    ("+266", _("+266 Lesotho")),
    ("+231", _("+231 Liberia")),
    ("+218", _("+218 Libya")),
    ("+423", _("+423 Liechtenstein")),
    ("+370", _("+370 Lithuania")),
    ("+352", _("+352 Luxembourg")),
    ("+853", _("+853 Macau")),
    ("+389", _("+389 Macedonia")),
    ("+261", _("+261 Madagascar")),
    ("+265", _("+265 Malawi")),
    ("+60", _("+60 Malaysia")),
    ("+960", _("+960 Maldives")),
    ("+223", _("+223 Mali")),
    ("+356", _("+356 Malta")),
    ("+692", _("+692 Marshall Islands")),
    ("+222", _("+222 Mauritania")),
    ("+230", _("+230 Mauritius")),
    ("+262", _("+262 Mayotte")),
    ("+52", _("+52 Mexico")),
    ("+691", _("+691 Micronesia")),
    ("+373", _("+373 Moldova")),
    ("+377", _("+377 Monaco")),
    ("+976", _("+976 Mongolia")),
    ("+382", _("+382 Montenegro")),
    ("+1-664", _("+1-664 Montserrat")),
    ("+212", _("+212 Morocco")),
    ("+258", _("+258 Mozambique")),
    ("+95", _("+95 Myanmar")),
    ("+264", _("+264 Namibia")),
    ("+674", _("+674 Nauru")),
    ("+977", _("+977 Nepal")),
    ("+31", _("+31 Netherlands")),
    ("+64", _("+64 New Zealand")),
    ("+505", _("+505 Nicaragua")),
    ("+227", _("+227 Niger")),
    ("+234", _("+234 Nigeria")),
    ("+683", _("+683 Niue")),
    ("+47", _("+47 Norway")),
    ("+968", _("+968 Oman")),
    ("+92", _("+92 Pakistan")),
    ("+680", _("+680 Palau")),
    ("+507", _("+507 Panama")),
    ("+675", _("+675 Papua New Guinea")),
    ("+595", _("+595 Paraguay")),
    ("+51", _("+51 Peru")),
    ("+63", _("+63 Philippines")),
    ("+48", _("+48 Poland")),
    ("+351", _("+351 Portugal")),
    ("+1-787", _("+1-787 Puerto Rico")),
    ("+974", _("+974 Qatar")),
    ("+262", _("+262 Réunion")),
    ("+40", _("+40 Romania")),
    ("+7", _("+7 Russia")),
    ("+250", _("+250 Rwanda")),
    ("+1-869", _("+1-869 Saint Kitts and Nevis")),
    ("+1-758", _("+1-758 Saint Lucia")),
    ("+1-784", _("+1-784 Saint Vincent and the Grenadines")),
    ("+685", _("+685 Samoa")),
    ("+378", _("+378 San Marino")),
    ("+239", _("+239 Sao Tome and Principe")),
    ("+966", _("+966 Saudi Arabia")),
    ("+221", _("+221 Senegal")),
    ("+381", _("+381 Serbia")),
    ("+248", _("+248 Seychelles")),
    ("+232", _("+232 Sierra Leone")),
    ("+65", _("+65 Singapore")),
    ("+421", _("+421 Slovakia")),
    ("+386", _("+386 Slovenia")),
    ("+677", _("+677 Solomon Islands")),
    ("+252", _("+252 Somalia")),
    ("+27", _("+27 South Africa")),
    ("+34", _("+34 Spain")),
    ("+94", _("+94 Sri Lanka")),
    ("+249", _("+249 Sudan")),
    ("+597", _("+597 Suriname")),
    ("+268", _("+268 Swaziland")),
    ("+46", _("+46 Sweden")),
    ("+41", _("+41 Switzerland")),
    ("+963", _("+963 Syria")),
)

INDUSTRY_CHOICES = [
    ("", _("Choose industry")),

    # Technology & Software
    ("it", _("IT & Software")),
    ("saas", _("Software Development / SaaS")),
    ("software_services", _("Information Technology & Services")),
    ("ai", _("Artificial Intelligence / Machine Learning")),
    ("security", _("Cybersecurity")),
    ("cloud", _("Cloud Computing")),
    ("blockchain", _("Web3 / Blockchain / Crypto")),
    ("gaming", _("Gaming / Esports")),
    ("hardware", _("Hardware / Semiconductors")),
    ("telecom", _("Telecommunications")),
    ("data", _("Data & Analytics")),

    # Media / Entertainment
    ("social_media", _("Social Media / Digital Media")),
    ("creator_economy", _("Content Creation / Influencer Marketing")),
    ("film", _("Film, TV & Video Production")),
    ("music", _("Music & Audio")),
    ("publishing", _("Publishing")),
    ("marketing", _("Advertising & Marketing")),
    ("pr", _("Public Relations")),
    ("animation", _("Animation / VFX")),
    ("photography", _("Photography")),
    ("journalism", _("Journalism / News Media")),
    ("podcasting", _("Podcasting")),
    ("streaming", _("Streaming & OTT")),

    # Ecommerce & Retail
    ("ecommerce", _("E-commerce")),
    ("retail", _("Retail")),
    ("fashion", _("Fashion & Apparel")),
    ("beauty", _("Beauty & Cosmetics")),
    ("consumer_electronics", _("Consumer Electronics")),
    ("luxury", _("Luxury Goods")),
    ("dtc", _("Direct-to-Consumer (DTC) Brands")),

    # Finance & Business
    ("finance", _("Banking")),
    ("fintech", _("FinTech")),
    ("insurance", _("Insurance")),
    ("investment", _("Investment / Asset Management")),
    ("vc_pe", _("Venture Capital / Private Equity")),
    ("accounting", _("Accounting & Auditing")),
    ("consulting", _("Consulting")),
    ("legal", _("Legal Services")),
    ("real_estate", _("Real Estate")),
    ("hr", _("Human Resources / Staffing")),

    # Food & Hospitality
    ("food", _("Food & Beverage")),
    ("restaurant", _("Restaurants / QSR")),
    ("hospitality", _("Hospitality / Hotels")),
    ("tourism", _("Travel & Tourism")),
    ("event", _("Events & Event Management")),

    # Health
    ("healthcare", _("Healthcare")),
    ("pharma", _("Pharmaceuticals")),
    ("biotech", _("Biotechnology")),
    ("medical_devices", _("Medical Devices")),
    ("fitness", _("Fitness & Wellness")),
    ("mental_health", _("Mental Health Services")),
    ("nutrition", _("Nutrition & Supplements")),

    # Education
    ("education", _("Education / EdTech")),
    ("elearning", _("E-learning / Online Courses")),
    ("higher_education", _("Higher Education")),
    ("tutoring", _("Test Prep / Tutoring")),

    # Manufacturing / Industrial
    ("manufacturing", _("Manufacturing")),
    ("automobile", _("Automotive")),
    ("aerospace", _("Aerospace & Defense")),
    ("construction", _("Construction")),
    ("engineering", _("Engineering")),
    ("industrial_equipment", _("Industrial Equipment")),
    ("textiles", _("Textiles")),

    # Energy / Environment
    ("oil_gas", _("Energy (Oil & Gas)")),
    ("renewable_energy", _("Renewable Energy")),
    ("utilities", _("Utilities")),
    ("environment", _("Environmental Services / Sustainability")),
    ("agriculture", _("Agriculture & Farming")),
    ("mining", _("Mining")),

    # Non-profit / Government
    ("nonprofit", _("Non-Profit / NGO")),
    ("government", _("Government / Public Sector")),
    ("religious", _("Religious Organizations")),
    ("politics", _("Politics / Advocacy")),

    # Sports / Recreation
    ("sports", _("Sports & Sports Management")),
    ("outdoor", _("Outdoor & Recreation")),
    ("toys_games", _("Toys & Games")),

    # Other
    ("logistics", _("Logistics & Supply Chain")),
    ("transport", _("Transportation")),
    ("pet_care", _("Pet Care")),
    ("home_design", _("Home & Interior Design")),
    ("art_design", _("Art & Design")),
    ("architecture", _("Architecture")),
    ("other", _("Other")),
]