# Generated by Django 6.0.2 on 2026-05-11 13:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0017_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex="^[\\w\\s(),.'’:/\\-]+$")], verbose_name='job title')),
                ('desc', models.TextField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex="^[\\w\\s(),.'’:/\\-]+$")], verbose_name='job description')),
                ('type', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('CT', 'Contract'), ('RM', 'Remote')], default='FT', max_length=2, verbose_name='job type')),
                ('platform', models.CharField(help_text='the platform this job is connected to', verbose_name='job platform')),
                ('location', models.CharField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex="^[\\w\\s(),.'’:/\\-]+$")], verbose_name='job location')),
                ('requirements', models.TextField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex="^[\\w\\s(),.'’:/\\-]+$")], verbose_name='job requirements and skills')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='minmum salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum salary')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_expires', models.DateTimeField(help_text='The date and time until which this job remains publicly visible.', verbose_name='date expires')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to deactivate this job posting without deleting it.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobposting_related', related_query_name='company_jobposting_query', to='company.company', verbose_name='company')),
                ('recruter', models.ForeignKey(limit_choices_to={'groups__name__in': ['company', 'creator']}, on_delete=django.db.models.deletion.CASCADE, related_name='recruter_jobposting_related', related_query_name='recruter_jobposting_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'job Posting',
                'verbose_name_plural': 'job Postings',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.JSONField(verbose_name='answer')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', verbose_name='Application status')),
                ('status_reason', models.TextField(null=True, verbose_name='reason')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('applicant', models.ForeignKey(limit_choices_to={'groups__name__in': ['talent']}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_jobapplicant_related', related_query_name='applicant_jobapplicant_query', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_jobapplicant_related', related_query_name='job_jobapplicant_query', to='job.jobposting', verbose_name='job')),
            ],
            options={
                'verbose_name': 'job applicant',
                'verbose_name_plural': 'job applicants',
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField(verbose_name='form structure')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_customquestion_related', related_query_name='job_customquestion_query', to='job.jobposting', verbose_name='user')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-date_created', '-date_updated'],
            },
        ),
    ]
