# Generated by Django 5.2.14 on 2026-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='exp_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum experiance'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='exp_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='minmum experiance'),
        ),
    ]
