# Generated by Django 5.2.14 on 2026-06-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobposting_exp_max_jobposting_exp_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='exp_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum experiance'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='exp_min',
            field=models.IntegerField(default=0, verbose_name='minmum experiance'),
        ),
    ]
