# Generated by Django 5.2.14 on 2026-06-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobposting_exp_max_alter_jobposting_exp_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='tags',
            field=models.CharField(default='job', help_text="use ',' to seprate tags", verbose_name='tags'),
            preserve_default=False,
        ),
    ]
