# Generated by Django 5.2.14 on 2026-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobposting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='status_reason',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
