# Generated by Django 6.0.6 on 2026-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobapplicant_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='answer',
            field=models.JSONField(blank=True, null=True, verbose_name='answer'),
        ),
    ]
