# Generated by Django 6.0.6 on 2026-06-19 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobapplicant_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='desc',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='job description'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='job location'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='job requirements and skills'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='job title'),
        ),
    ]
