# Generated by Django 6.0.6 on 2026-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_jobposting_desc_alter_jobposting_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='tags',
            field=models.CharField(blank=True, help_text="use ',' to seprate tags", null=True, verbose_name='tags (optional)'),
        ),
    ]
