# Generated by Django 6.0.6 on 2026-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_jobposting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='platform',
            field=models.CharField(verbose_name='job platform'),
        ),
    ]
