# Generated by Django 6.0.6 on 2026-06-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_jobposting_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='platform',
            field=models.CharField(help_text='The platform this job is connected to. <a href="/accounts/connect/" class="text-primary underline">Connect account</a>', verbose_name='job platform'),
        ),
    ]
