# Generated by Django 6.0.6 on 2026-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_jobposting_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='platform',
            field=models.CharField(help_text='The platform this job is connected to. ', verbose_name='job platform'),
        ),
    ]
