# Generated by Django 6.0.6 on 2026-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_jobposting_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='exp_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum experience in years'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='exp_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='minmum experience in years'),
        ),
    ]
