# Generated by Django 6.0.2 on 2026-02-21 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_company_address', message='Please enter a valid company address (minimum 5 characters).', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='Company address'),
        ),
    ]
