# Generated by Django 6.0.2 on 2026-02-21 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_company_address', message='Please enter a valid company address.', regex='^[a-zA-Z0-9\\s/,\\.\\-\\n]+$')], verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Only contain letters, numbers, spaces, hyphens, slashes, commas, and new lines.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='Company bio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only contain letters, numbers, spaces, hyphens, slashes, commas, and new lines.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only contain letters, numbers, spaces, hyphens, slashes, commas, and new lines.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone number', regex='^\\\\+?[1-9][0-9]{7,14}$')], verbose_name='Number'),
        ),
    ]
