# Generated by Django 6.0.2 on 2026-02-21 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_address_alter_company_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone number. Please enter digits only (8-15 characters).', regex='^[1-9][0-9]{7,14}$')], verbose_name='Number'),
        ),
    ]
