# Generated by Django 6.0.2 on 2026-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='If checked, this company will be visible to all users.', verbose_name='Show on public listing'),
        ),
    ]
