# Generated by Django 6.0.2 on 2026-02-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='hirepedia', editable=False, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
