# Generated by Django 6.0.2 on 2026-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        ),
    ]
