# Generated by Django 6.0.2 on 2026-03-01 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_company_id_alter_company_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name__in': ['company']}, on_delete=django.db.models.deletion.CASCADE, related_name='related_company_user', related_query_name='query_company_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
