# Generated by Django 6.0.2 on 2026-03-09 13:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_created_at_alter_company_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_company_address', message='check your address for typos or unsupported characters.', regex='^[a-zA-Z0-9\\s/,\\.\\-\\n]+$')], verbose_name='company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='some characters aren’t supported. Use only letters, numbers, and basic punctuation.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='company bio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('AF', 'Afghanistan'), ('AX', 'Aland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas (The)'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia (Plurinational State of)'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo (the Democratic Republic of the)'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran (Islamic Republic of)'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', "Korea (the Democratic People's Republic of)"), ('KR', 'Korea (the Republic of)'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia (Federated States of)'), ('MD', 'Moldova (the Republic of)'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands (Kingdom of the)'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TW', 'Taiwan (Province of China)'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania, the United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Türkiye'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States of America'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela (Bolivarian Republic of)'), ('VN', 'Viet Nam'), ('VG', 'Virgin Islands (British)'), ('VI', 'Virgin Islands (U.S.)'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], default='IN', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employe_size',
            field=models.PositiveIntegerField(verbose_name='number of employe'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(max_length=100, validators=[django.core.validators.RegexValidator(message='some characters aren’t supported. Use only letters, numbers, and basic punctuation.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='if checked, this company will be visible to all users', verbose_name='show on public listing'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(verbose_name='company Logo url'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='some characters aren’t supported. Use only letters, numbers, and basic punctuation.', regex='^[a-zA-Z0-9\\s\\/,\\.\\-\\n]+$')], verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_company_related', related_query_name='phone_company_query', to='company.phonenumber', verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(verbose_name='company website url'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name__in': ['company']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_company_related', related_query_name='user_company_query', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='code',
            field=models.CharField(choices=[('+93', '+93 Afghanistan'), ('+358', '+358 Åland Islands'), ('+355', '+355 Albania'), ('+213', '+213 Algeria'), ('+1-684', '+1-684 American Samoa'), ('+376', '+376 Andorra'), ('+244', '+244 Angola'), ('+1-264', '+1-264 Anguilla'), ('+672', '+672 Antarctica'), ('+1-268', '+1-268 Antigua and Barbuda'), ('+54', '+54 Argentina'), ('+374', '+374 Armenia'), ('+297', '+297 Aruba'), ('+61', '+61 Australia'), ('+43', '+43 Austria'), ('+994', '+994 Azerbaijan'), ('+1-242', '+1-242 Bahamas'), ('+973', '+973 Bahrain'), ('+880', '+880 Bangladesh'), ('+1-246', '+1-246 Barbados'), ('+375', '+375 Belarus'), ('+32', '+32 Belgium'), ('+501', '+501 Belize'), ('+229', '+229 Benin'), ('+1-441', '+1-441 Bermuda'), ('+975', '+975 Bhutan'), ('+591', '+591 Bolivia'), ('+387', '+387 Bosnia and Herzegovina'), ('+267', '+267 Botswana'), ('+55', '+55 Brazil'), ('+246', '+246 British Indian Ocean Territory'), ('+673', '+673 Brunei'), ('+359', '+359 Bulgaria'), ('+226', '+226 Burkina Faso'), ('+257', '+257 Burundi'), ('+855', '+855 Cambodia'), ('+237', '+237 Cameroon'), ('+1', '+1 Canada'), ('+238', '+238 Cape Verde'), ('+1-345', '+1-345 Cayman Islands'), ('+236', '+236 Central African Republic'), ('+235', '+235 Chad'), ('+56', '+56 Chile'), ('+86', '+86 China'), ('+61', '+61 Christmas Island'), ('+61', '+61 Cocos Islands'), ('+57', '+57 Colombia'), ('+269', '+269 Comoros'), ('+242', '+242 Congo'), ('+243', '+243 DR Congo'), ('+682', '+682 Cook Islands'), ('+506', '+506 Costa Rica'), ('+385', '+385 Croatia'), ('+53', '+53 Cuba'), ('+599', '+599 Curacao'), ('+357', '+357 Cyprus'), ('+420', '+420 Czech Republic'), ('+45', '+45 Denmark'), ('+253', '+253 Djibouti'), ('+1-767', '+1-767 Dominica'), ('+1-809', '+1-809 Dominican Republic'), ('+670', '+670 East Timor'), ('+593', '+593 Ecuador'), ('+20', '+20 Egypt'), ('+503', '+503 El Salvador'), ('+240', '+240 Equatorial Guinea'), ('+291', '+291 Eritrea'), ('+372', '+372 Estonia'), ('+251', '+251 Ethiopia'), ('+500', '+500 Falkland Islands'), ('+298', '+298 Faroe Islands'), ('+679', '+679 Fiji'), ('+358', '+358 Finland'), ('+33', '+33 France'), ('+689', '+689 French Polynesia'), ('+241', '+241 Gabon'), ('+220', '+220 Gambia'), ('+995', '+995 Georgia'), ('+49', '+49 Germany'), ('+233', '+233 Ghana'), ('+350', '+350 Gibraltar'), ('+30', '+30 Greece'), ('+299', '+299 Greenland'), ('+1-473', '+1-473 Grenada'), ('+1-671', '+1-671 Guam'), ('+502', '+502 Guatemala'), ('+44-1481', '+44-1481 Guernsey'), ('+224', '+224 Guinea'), ('+245', '+245 Guinea-Bissau'), ('+592', '+592 Guyana'), ('+509', '+509 Haiti'), ('+504', '+504 Honduras'), ('+852', '+852 Hong Kong'), ('+36', '+36 Hungary'), ('+354', '+354 Iceland'), ('+91', '+91 India'), ('+62', '+62 Indonesia'), ('+98', '+98 Iran'), ('+964', '+964 Iraq'), ('+353', '+353 Ireland'), ('+972', '+972 Israel'), ('+39', '+39 Italy'), ('+225', '+225 Ivory Coast'), ('+1-876', '+1-876 Jamaica'), ('+81', '+81 Japan'), ('+962', '+962 Jordan'), ('+7', '+7 Kazakhstan'), ('+254', '+254 Kenya'), ('+686', '+686 Kiribati'), ('+965', '+965 Kuwait'), ('+996', '+996 Kyrgyzstan'), ('+856', '+856 Laos'), ('+371', '+371 Latvia'), ('+961', '+961 Lebanon'), ('+266', '+266 Lesotho'), ('+231', '+231 Liberia'), ('+218', '+218 Libya'), ('+423', '+423 Liechtenstein'), ('+370', '+370 Lithuania'), ('+352', '+352 Luxembourg'), ('+853', '+853 Macau'), ('+389', '+389 Macedonia'), ('+261', '+261 Madagascar'), ('+265', '+265 Malawi'), ('+60', '+60 Malaysia'), ('+960', '+960 Maldives'), ('+223', '+223 Mali'), ('+356', '+356 Malta'), ('+692', '+692 Marshall Islands'), ('+222', '+222 Mauritania'), ('+230', '+230 Mauritius'), ('+262', '+262 Mayotte'), ('+52', '+52 Mexico'), ('+691', '+691 Micronesia'), ('+373', '+373 Moldova'), ('+377', '+377 Monaco'), ('+976', '+976 Mongolia'), ('+382', '+382 Montenegro'), ('+1-664', '+1-664 Montserrat'), ('+212', '+212 Morocco'), ('+258', '+258 Mozambique'), ('+95', '+95 Myanmar'), ('+264', '+264 Namibia'), ('+674', '+674 Nauru'), ('+977', '+977 Nepal'), ('+31', '+31 Netherlands'), ('+64', '+64 New Zealand'), ('+505', '+505 Nicaragua'), ('+227', '+227 Niger'), ('+234', '+234 Nigeria'), ('+683', '+683 Niue'), ('+47', '+47 Norway'), ('+968', '+968 Oman'), ('+92', '+92 Pakistan'), ('+680', '+680 Palau'), ('+507', '+507 Panama'), ('+675', '+675 Papua New Guinea'), ('+595', '+595 Paraguay'), ('+51', '+51 Peru'), ('+63', '+63 Philippines'), ('+48', '+48 Poland'), ('+351', '+351 Portugal'), ('+1-787', '+1-787 Puerto Rico'), ('+974', '+974 Qatar'), ('+262', '+262 Réunion'), ('+40', '+40 Romania'), ('+7', '+7 Russia'), ('+250', '+250 Rwanda'), ('+1-869', '+1-869 Saint Kitts and Nevis'), ('+1-758', '+1-758 Saint Lucia'), ('+1-784', '+1-784 Saint Vincent and the Grenadines'), ('+685', '+685 Samoa'), ('+378', '+378 San Marino'), ('+239', '+239 Sao Tome and Principe'), ('+966', '+966 Saudi Arabia'), ('+221', '+221 Senegal'), ('+381', '+381 Serbia'), ('+248', '+248 Seychelles'), ('+232', '+232 Sierra Leone'), ('+65', '+65 Singapore'), ('+421', '+421 Slovakia'), ('+386', '+386 Slovenia'), ('+677', '+677 Solomon Islands'), ('+252', '+252 Somalia'), ('+27', '+27 South Africa'), ('+34', '+34 Spain'), ('+94', '+94 Sri Lanka'), ('+249', '+249 Sudan'), ('+597', '+597 Suriname'), ('+268', '+268 Swaziland'), ('+46', '+46 Sweden'), ('+41', '+41 Switzerland'), ('+963', '+963 Syria')], default='+91', max_length=8, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='enter a valid phone number (8–15 digits)', regex='^[1-9][0-9]{7,14}$')], verbose_name='number'),
        ),
    ]
