# Generated by Django 6.0.2 on 2026-03-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_historicalcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
    ]
