# Generated by Django 6.0.2 on 2026-03-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_delete_historicalcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(choices=[('', 'Choose industry'), ('it', 'IT & Software'), ('ai', 'Artificial Intelligence'), ('fintech', 'FinTech'), ('finance', 'Finance & Banking'), ('insurance', 'Insurance'), ('healthcare', 'Healthcare'), ('pharma', 'Pharmaceuticals'), ('biotech', 'Biotechnology'), ('education', 'Education'), ('edtech', 'EdTech'), ('manufacturing', 'Manufacturing'), ('automobile', 'Automobile'), ('aerospace', 'Aerospace'), ('construction', 'Construction'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('ecommerce', 'E-commerce'), ('logistics', 'Logistics & Supply Chain'), ('transport', 'Transportation'), ('hospitality', 'Hospitality'), ('tourism', 'Tourism & Travel'), ('food', 'Food & Beverage'), ('agriculture', 'Agriculture'), ('energy', 'Energy & Utilities'), ('renewable_energy', 'Renewable Energy'), ('telecom', 'Telecommunications'), ('media', 'Media & Entertainment'), ('gaming', 'Gaming'), ('marketing', 'Marketing & Advertising'), ('hr', 'Human Resources'), ('legal', 'Legal Services'), ('consulting', 'Consulting'), ('nonprofit', 'Non-Profit / NGO'), ('government', 'Government & Public Sector'), ('security', 'Cybersecurity'), ('data', 'Data & Analytics'), ('blockchain', 'Blockchain & Web3'), ('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('sports', 'Sports & Fitness'), ('event', 'Event Management')], default='', max_length=100, verbose_name='industry'),
        ),
    ]
