# Generated by Django 5.2.14 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, verbose_name='company email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, null=True, verbose_name='company tagline (Optional)'),
        ),
    ]
