# Generated by Django 6.0.6 on 2026-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_email_company_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(choices=[('', 'Choose industry'), ('it', 'IT & Software'), ('saas', 'Software Development / SaaS'), ('software_services', 'Information Technology & Services'), ('ai', 'Artificial Intelligence / Machine Learning'), ('security', 'Cybersecurity'), ('cloud', 'Cloud Computing'), ('blockchain', 'Web3 / Blockchain / Crypto'), ('gaming', 'Gaming / Esports'), ('hardware', 'Hardware / Semiconductors'), ('telecom', 'Telecommunications'), ('data', 'Data & Analytics'), ('social_media', 'Social Media / Digital Media'), ('creator_economy', 'Content Creation / Influencer Marketing'), ('film', 'Film, TV & Video Production'), ('music', 'Music & Audio'), ('publishing', 'Publishing'), ('marketing', 'Advertising & Marketing'), ('pr', 'Public Relations'), ('animation', 'Animation / VFX'), ('photography', 'Photography'), ('journalism', 'Journalism / News Media'), ('podcasting', 'Podcasting'), ('streaming', 'Streaming & OTT'), ('ecommerce', 'E-commerce'), ('retail', 'Retail'), ('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('consumer_electronics', 'Consumer Electronics'), ('luxury', 'Luxury Goods'), ('dtc', 'Direct-to-Consumer (DTC) Brands'), ('finance', 'Banking'), ('fintech', 'FinTech'), ('insurance', 'Insurance'), ('investment', 'Investment / Asset Management'), ('vc_pe', 'Venture Capital / Private Equity'), ('accounting', 'Accounting & Auditing'), ('consulting', 'Consulting'), ('legal', 'Legal Services'), ('real_estate', 'Real Estate'), ('hr', 'Human Resources / Staffing'), ('food', 'Food & Beverage'), ('restaurant', 'Restaurants / QSR'), ('hospitality', 'Hospitality / Hotels'), ('tourism', 'Travel & Tourism'), ('event', 'Events & Event Management'), ('healthcare', 'Healthcare'), ('pharma', 'Pharmaceuticals'), ('biotech', 'Biotechnology'), ('medical_devices', 'Medical Devices'), ('fitness', 'Fitness & Wellness'), ('mental_health', 'Mental Health Services'), ('nutrition', 'Nutrition & Supplements'), ('education', 'Education / EdTech'), ('elearning', 'E-learning / Online Courses'), ('higher_education', 'Higher Education'), ('tutoring', 'Test Prep / Tutoring'), ('manufacturing', 'Manufacturing'), ('automobile', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('construction', 'Construction'), ('engineering', 'Engineering'), ('industrial_equipment', 'Industrial Equipment'), ('textiles', 'Textiles'), ('oil_gas', 'Energy (Oil & Gas)'), ('renewable_energy', 'Renewable Energy'), ('utilities', 'Utilities'), ('environment', 'Environmental Services / Sustainability'), ('agriculture', 'Agriculture & Farming'), ('mining', 'Mining'), ('nonprofit', 'Non-Profit / NGO'), ('government', 'Government / Public Sector'), ('religious', 'Religious Organizations'), ('politics', 'Politics / Advocacy'), ('sports', 'Sports & Sports Management'), ('outdoor', 'Outdoor & Recreation'), ('toys_games', 'Toys & Games'), ('logistics', 'Logistics & Supply Chain'), ('transport', 'Transportation'), ('pet_care', 'Pet Care'), ('home_design', 'Home & Interior Design'), ('art_design', 'Art & Design'), ('architecture', 'Architecture'), ('other', 'Other')], default='', max_length=100, verbose_name='industry'),
        ),
    ]
