# Generated by Django 6.0.2 on 2026-04-16 15:20

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('frm', models.DateField(blank=True, null=True, verbose_name='from')),
                ('to', models.DateField(blank=True, null=True, verbose_name='to')),
                ('description', models.TextField(verbose_name='description')),
                ('is_present', models.BooleanField(default=False, verbose_name='Presently wokring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience_related', related_query_name='user_experience_query', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experiance',
                'verbose_name_plural': 'experiances',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(editable=False, unique=True)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('content_creator', 'Content Creator'), ('video_editor', 'Video Editor'), ('channel_manager', 'Channel / Account Manager'), ('live_streamer', 'Live Streamer'), ('community_manager', 'Community Manager'), ('moderator', 'Moderator'), ('growth_specialist', 'Growth Specialist'), ('social_media_manager', 'Social Media Manager'), ('ads_specialist', 'Ads / Performance Marketing Specialist'), ('brand_manager', 'Brand Manager'), ('script_writer', 'Script Writer'), ('thumbnail_designer', 'Thumbnail / Graphic Designer'), ('seo_specialist', 'SEO / Content Optimization Specialist'), ('analyst', 'Analytics & Insights Specialist'), ('multi_role', 'Multi-Role / Generalist')], help_text='Choose your primary talent first. It will be displayed on your profile.', max_length=100, verbose_name='Specialization')),
                ('about', models.TextField(verbose_name='about')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('experiences', models.ManyToManyField(blank=True, related_name='experiences_portfolio_related', related_query_name='experiences_portfolio_query', to='portfolio.experience', verbose_name='experiences')),
                ('languages', models.ManyToManyField(blank=True, related_name='languages_portfolio_related', related_query_name='languages_portfolio_query', to='portfolio.language', verbose_name='languages')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name__in': ['talent']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio_related', related_query_name='user_portfolio_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
        ),
    ]
