# Generated by Django 6.0.2 on 2026-04-16 15:24

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(help_text='Paste YouTube, Vimeo, or other video link')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('content_creator', 'Content Creator'), ('video_editor', 'Video Editor'), ('channel_manager', 'Channel / Account Manager'), ('live_streamer', 'Live Streamer'), ('community_manager', 'Community Manager'), ('moderator', 'Moderator'), ('growth_specialist', 'Growth Specialist'), ('social_media_manager', 'Social Media Manager'), ('ads_specialist', 'Ads / Performance Marketing Specialist'), ('brand_manager', 'Brand Manager'), ('script_writer', 'Script Writer'), ('thumbnail_designer', 'Thumbnail / Graphic Designer'), ('seo_specialist', 'SEO / Content Optimization Specialist'), ('analyst', 'Analytics & Insights Specialist'), ('multi_role', 'Multi-Role / Generalist')], max_length=100, verbose_name='Specialization')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('discord', 'Discord'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitch', 'Twitch')], default='youtube', max_length=100, verbose_name='platform')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_related', related_query_name='user_video_query', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['creator']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_videos_related', related_query_name='verified_by_videos_query', to=settings.AUTH_USER_MODEL, verbose_name='Verifier')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'vidoes',
                'permissions': [('can_verify', 'Can Verify this video')],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos_portfolio_related', related_query_name='videos_portfolio_query', to='portfolio.video', verbose_name='videos'),
        ),
    ]
