# Generated by Django 6.0.2 on 2026-04-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'permissions': [('can_verify', 'Can Verify this video'), ('can_view_verified_work', 'Can View Verified work')], 'verbose_name': 'video', 'verbose_name_plural': 'vidoes'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='extra_data',
        ),
    ]
