# Generated by Django 6.0.2 on 2026-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_video_options_remove_video_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
