# Generated by Django 6.0.2 on 2026-04-22 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_video_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0, verbose_name='Followers, subscribers count')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('discord', 'Discord'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitch', 'Twitch')], default='youtube', max_length=100, verbose_name='platform')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'groups__name__in': ['creator']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_creatorcount_related', related_query_name='user_creatorcount_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'creator count',
                'verbose_name_plural': 'creator counts',
            },
        ),
    ]
