# Generated by Django 6.0.2 on 2026-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_creatorcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='extra data'),
        ),
    ]
