# Generated by Django 6.0.2 on 2026-04-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_video_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='extra_data',
        ),
    ]
