# Generated by Django 6.0.2 on 2026-04-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_video_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcount',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['creator']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_creatorcount_related', related_query_name='user_creatorcount_query', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
