# Generated by Django 6.0.2 on 2026-04-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_creatorcount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagdesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('discord', 'Discord'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitch', 'Twitch')], max_length=100, verbose_name='platform')),
                ('badge', models.CharField(choices=[('br', 'Bronze'), ('si', 'Silver'), ('go', 'Gold'), ('di', 'Diamond')], default='br', verbose_name='badge')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'groups__name__in': ['talent']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_badgehistory_related', related_query_name='user_badgehistory_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('video', models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='video_badgehistory_related', related_query_name='video_badgehistory_query', to='portfolio.video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'badge history',
                'verbose_name_plural': 'badge history',
            },
        ),
    ]
