# Generated by Django 6.0.2 on 2026-04-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_bagdeshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagdeshistory',
            name='platform',
        ),
    ]
