# Generated by Django 6.0.2 on 2026-04-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_bagdeshistory_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagdeshistory',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_badgehistory_related', related_query_name='creator_badgehistory_query', to='portfolio.creatorcount', verbose_name='creater'),
            preserve_default=False,
        ),
    ]
