# Generated by Django 6.0.2 on 2026-04-26 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_bagdeshistory_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.IntegerField(default=0, verbose_name='point')),
                ('date_expire', models.DateTimeField(verbose_name='expire date')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='redeemed')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name__in': ['creator']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_point_related', related_query_name='user_point_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('video', models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='video_point_related', related_query_name='video_point_query', to='portfolio.video', verbose_name='video')),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': "point's",
            },
        ),
    ]
