# Generated by Django 6.0.2 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='point'),
        ),
    ]
