# Generated by Django 6.0.2 on 2026-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_point_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='extra data'),
        ),
        migrations.AddField(
            model_name='video',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='video data'),
        ),
    ]
