# Generated by Django 6.0.2 on 2026-05-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_portfolio_extra_data_video_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='extra_data',
        ),
    ]
