# Generated by Django 5.2.14 on 2026-05-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_portfolio_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagdeshistory',
            name='creator',
        ),
        migrations.DeleteModel(
            name='CreatorCount',
        ),
    ]
