# Generated by Django 5.2.14 on 2026-06-04 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_bagdeshistory_creator_delete_creatorcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='frm',
            field=models.DateField(default=datetime.datetime(2026, 6, 4, 16, 21, 31, 221771, tzinfo=datetime.timezone.utc), verbose_name='from'),
            preserve_default=False,
        ),
    ]
