# Generated by Django 5.2.14 on 2026-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_experience_frm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='description (optional)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title (optional)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to',
            field=models.DateField(blank=True, null=True, verbose_name='to (optional)'),
        ),
    ]
