# Generated by Django 6.0.6 on 2026-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='frm',
            field=models.DateField(verbose_name='from (optional)'),
        ),
    ]
