# Generated by Django 6.0.2 on 2026-04-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_id',
        ),
    ]
