# Generated by Django 6.0.2 on 2026-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
