# Generated by Django 6.0.2 on 2026-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
