# Generated by Django 5.2.14 on 2026-06-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_user_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug Repor'), ('FEA', 'Feature Request'), ('GEN', 'General Feedback'), ('SUP', 'Support')], default='GEN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='desc',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='', max_length=225, verbose_name='subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_related', related_query_name='notification_recipient_query', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='This field contain data of connected platform', null=True, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.IntegerField(editable=False, unique=True, verbose_name='pid'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('SPM', 'Spam'), ('HST', 'Harassment'), ('FAP', 'Fake Profile'), ('INAP', 'Inappropriate Content'), ('SCAM', 'Scam or Fraud'), ('OTH', 'Others')], max_length=30, verbose_name='Reason')),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('REV', 'Reviewed'), ('RES', 'Resolved'), ('REJ', 'Rejected')], default='PEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_related', related_query_name='report_user_query', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
