# Generated by Django 5.2.14 on 2026-06-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_feedback_feedback_feedback_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
    ]
