# Generated by Django 5.2.14 on 2026-06-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_created'], 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
