# Generated by Django 5.2.14 on 2026-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
