# Generated by Django 5.2.14 on 2026-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_report_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('FEA', 'Feature Request'), ('GEN', 'General Feedback'), ('SUP', 'Support')], max_length=20),
        ),
    ]
