# Generated by Django 5.2.14 on 2026-06-06 17:41

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'giff'], message='only ".png", ".jpg"," .jpeg", ".giff" are allowed')], verbose_name='profile picture'),
        ),
    ]
