# Generated by Django 5.2.14 on 2026-06-06 17:45

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.get_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'giff'], message='only ".png", ".jpg"," .jpeg", ".giff" are allowed')], verbose_name='profile picture'),
        ),
    ]
