# Generated by Django 6.0.6 on 2026-06-19 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msg',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='contains invalid characters.', regex='^[\\s\\S]+$')], verbose_name='title'),
        ),
    ]
